# -*- coding: utf-8 -*-
# ================================================================================
# DISTILL.PY - STUDENT MODEL DISTILLATION FROM TEACHER TRACES
# ================================================================================
# This script performs supervised fine-tuning (SFT) of a student model using
# reasoning traces generated by the teacher model, potentially with antidistillation
# sampling (ADS) applied.
#
# Purpose in the ADS pipeline:
# - Test the effectiveness of antidistillation defense by attempting to distill
#   a student model from "poisoned" teacher traces
# - When lambda=0: baseline distillation with clean traces
# - When lambda>0: distillation with ADS-modified traces (should be less effective)
#
# Key functionality:
# 1. Load training traces (potentially poisoned with ADS) and holdout traces
# 2. Set up student model with optional LoRA for efficient fine-tuning
# 3. Perform supervised fine-tuning on completion-only portions (assistant responses)
# 4. Evaluate student performance to measure distillation effectiveness
# 5. Save the distilled model for subsequent evaluation
#
# Success metrics:
# - High student performance with lambda=0 indicates good baseline distillation
# - Low student performance with lambda>0 indicates effective ADS defense
# ================================================================================

import logging
import os
from io import StringIO
from types import SimpleNamespace

import datasets
import hydra
import torch
import yaml
import socket
from accelerate import Accelerator
from hydra.core.hydra_config import HydraConfig
from omegaconf import DictConfig, OmegaConf
from peft import LoraConfig, get_peft_model
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers import logging as hf_logging
from trl import DataCollatorForCompletionOnlyLM, SFTConfig, SFTTrainer

import wandb
from utils import (ANSWER_FORCE_STRING, SYSTEM_PROMPT, init, load_gsm8k,
                   load_hendrycks_math_dataset, load_mmlu)

# ================================================================================
# DISTRIBUTED SETUP AND LOGGING CONFIGURATION
# ================================================================================
accelerator = Accelerator()
log = logging.getLogger(__name__)

# Disable verbose logging for non-main processes to reduce noise
if not accelerator.is_main_process:
    hf_logging.set_verbosity_error()
    hf_logging.disable_progress_bar()
    datasets.disable_progress_bar()
    tqdm = lambda x, *args, **kwargs: x

def log_color(content, title=""):
    """Enhanced logging with colored console output for main process."""
    try:
        console = Console()
        console.print(Panel(content, title=title, border_style="cyan", title_align="left"))

        # Log the message as plain text for log files
        string_io = StringIO()
        plain_console = Console(file=string_io, highlight=False)
        plain_console.print(Panel(content, title=title, border_style="none", title_align="left"))
        log.info("\n" + string_io.getvalue())
    except Exception as e:
        log.error(f"Error logging content: {e}")

# ================================================================================
# MAIN DISTILLATION FUNCTION
# ================================================================================

@hydra.main(config_path=".", config_name="train_config", version_base="1.3")
def main(cfg: DictConfig):
    # ============================================================================
    # CONFIGURATION VALIDATION AND SETUP
    # ============================================================================
    # Validate required configurations for distillation
    # Set default tokenizer to match student model if not specified
    cfg.tokenizer = cfg.tokenizer or cfg.student
    

    # Initialize random seeds for reproducibility
    init(os.getenv("USER"), cfg.seed, "babel" in socket.gethostname())

    # Display configuration for debugging and reproducibility
    if accelerator.is_main_process:
        content = Syntax(OmegaConf.to_yaml(cfg, resolve=True), 'yaml', theme="monokai")
        log_color(content, title="Model Config")

    # Disable Weights & Biases if not needed
    if not cfg.wandb:
        os.environ["WANDB_DISABLED"] = "true"

    # ============================================================================
    # TOKENIZER SETUP
    # ============================================================================
    # Configure tokenizer to match the one used for trace generation
    # This ensures consistent tokenization between teacher traces and student training
    tokenizer = AutoTokenizer.from_pretrained(
        cfg.tokenizer,
        use_fast=True,
        fast_tokenizer=True,
        trust_remote_code=True,
        padding_side="left"  # Left padding for generation tasks
    )
    
    # Model-specific tokenizer configuration (consistent with gentraces.py)
    if "llama" in cfg.tokenizer.lower():
        eot_token_id = 128009
        eos_token_id = 128001
        tokenizer.pad_token_id = 128004
        tokenizer.eos_token_id = eos_token_id
        tokenizer.add_eos_token = False
    elif "qwen" in cfg.tokenizer.lower():
        eos_token = tokenizer.eos_token
        special_tokens = {"pad_token": "[PAD]"}
        tokenizer.add_special_tokens(special_tokens)
    else:
        raise ValueError(f"Unknown tokenizer {cfg.tokenizer}")

    # ============================================================================
    # STUDENT MODEL SETUP
    # ============================================================================
    # Load the student model that will learn from teacher traces
    # This is the "attacking" model attempting to steal teacher capabilities
    student = AutoModelForCausalLM.from_pretrained(
        cfg.student,
        trust_remote_code=True,
        # attn_implementation="sdpa",  # Use PyTorch SDPA instead of Flash Attention
        attn_implementation="flash_attention_2",
        torch_dtype=torch.bfloat16,  # Mixed precision for memory efficiency
        use_cache=True,
    )
    student.generation_config.pad_token_id = tokenizer.pad_token_id
    student.generation_config.add_eos_token = False

    # ============================================================================
    # LORA CONFIGURATION (OPTIONAL)
    # ============================================================================
    # Apply LoRA (Low-Rank Adaptation) for parameter-efficient fine-tuning
    # This is especially useful for large student models to reduce memory usage
    # In separate hyperparameter experiments, we have noticed that LoRA improves distillation effectiveness even when full finetuning is possible.
    if cfg.lora:
        peft_config = LoraConfig(
            r=cfg.lora_r,                    # Rank of adaptation matrices
            lora_alpha=cfg.lora_alpha,       # Scaling factor for LoRA
            target_modules=['q_proj','k_proj','v_proj','o_proj','gate_proj','up_proj','down_proj'],  # Target attention and MLP layers
            lora_dropout=cfg.lora_dropout,   # Dropout for LoRA layers
            bias="none",                     # No bias adaptation
            task_type="CAUSAL_LM",          # Causal language modeling task
        )
        student = get_peft_model(student, peft_config)

    # ============================================================================
    # DATASET PREPROCESSING
    # ============================================================================
    # Preprocess training and evaluation traces on the main process
    if accelerator.is_main_process:
        # Determine suffix length for different tokenizers to remove extra tokens
        suffix_len = -1 if "llama" in cfg.tokenizer.lower() else -2
        
        def preprocess_function(examples):
            """
            Preprocess reasoning traces for supervised fine-tuning.
            
            Converts teacher traces into chat format for student training:
            - Extracts assistant responses from teacher traces
            - Creates chat messages with system prompt, user problem, and assistant response
            - Tokenizes into format suitable for completion-only training
            """
            trace_colname = 'solution'
            responses = []
            
            for response in examples[trace_colname]:
                fixed_response = response + tokenizer.eos_token
                responses.append(fixed_response)
            
            # Create chat format messages for each example
            messages = [[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": problem.strip()},
                {"role": "assistant", "content": response.strip()}]
                for problem, response in zip(examples["problem"], responses)]
            
            # Apply chat template and tokenize
            tokens = tokenizer.apply_chat_template(messages, add_generation_prompt=False)
            tokens = [toks[:suffix_len] for toks in tokens]  # Remove extra tokens
            tok_lengths = [len(toks) for toks in tokens]
            return {"input_ids": tokens, "token_lengths": tok_lengths}

        if "gsm8k" in cfg.train_traces:
            dataset = load_gsm8k(split=cfg.train_traces.split("_")[1])
        elif "math" in cfg.train_traces:
            dataset = load_hendrycks_math_dataset(split=cfg.train_traces.split("_")[2])
        elif "mmlu" in cfg.train_traces:
            dataset = load_mmlu(split=cfg.train_traces.split("_")[1])
        else:
            raise ValueError(f"Unknown dataset and split: {cfg.train_traces}")
        
            
        train_traces = dataset.map(
            preprocess_function,
            batched=True,
            batch_size=16384,
            num_proc=96,
            remove_columns=list(dataset.column_names),
            desc="Preprocessing train dataset",
            load_from_cache_file=True
        )
        train_traces = train_traces.filter(lambda x: x["token_lengths"] <= cfg.max_length)
        if cfg.max_samples is not None:
            train_traces = train_traces.take(min(cfg.max_samples, len(train_traces)))
        log_color(tokenizer.decode(train_traces[0]['input_ids']), title="Example Input")
        train_token_length_stats = train_traces.to_pandas()["token_lengths"].describe()
        log_color(str(train_token_length_stats.round(2)), title="Train Trace Token Lengths")
        train_traces = train_traces.remove_columns("token_lengths")
        # train_traces.save_to_disk("/tmp/cached_train_traces")

    
    # Synchronize processes and load cached datasets
    accelerator.wait_for_everyone()
    # train_traces = datasets.load_from_disk("/tmp/cached_train_traces")
    # holdout_traces = datasets.load_from_disk("/tmp/cached_holdout_traces")

    # ============================================================================
    # DATA COLLATOR SETUP FOR COMPLETION-ONLY TRAINING
    # ============================================================================
    # Set up completion-only training to compute loss only on assistant responses
    # This is crucial for distillation as we want the student to learn the reasoning
    # patterns from the teacher, not just copy the entire input
    if 'llama' in cfg.student.lower():
        response_string = "<|start_header_id|>assistant<|end_header_id|>\n\n"
    elif "qwen" in cfg.student.lower():
        response_string = "<|im_start|>assistant\n"
    else:
        raise ValueError(f"Unknown model {cfg.student}")
    
    collator = DataCollatorForCompletionOnlyLM(
        response_template=tokenizer.encode(response_string, add_special_tokens=False),
        tokenizer=tokenizer,
        mlm=False  # Not using masked language modeling
    )

    # ============================================================================
    # TRAINING CONFIGURATION AND SETUP
    # ============================================================================
    # Configure training parameters and create SFT trainer
    steps_per_epoch = len(train_traces) // cfg.batch_size
    
    trainer = SFTTrainer(
        model=student,
        train_dataset=train_traces,
        processing_class=tokenizer,
        data_collator=collator,
        args=SFTConfig(
            bf16=student.config.use_bfloat16,  # Use bfloat16 if model supports it
            max_length=cfg.max_length,
            eval_strategy="no",
            eval_on_start= False,
            gradient_accumulation_steps=cfg.batch_size // cfg.per_device_batch_size // accelerator.num_processes,
            max_grad_norm=cfg.max_grad_norm,   # Gradient clipping for stability
            gradient_checkpointing=False,      # Disabled for speed
            gradient_checkpointing_kwargs={"use_reentrant": False},
            learning_rate=cfg.lr,
            weight_decay=cfg.weight_decay,
            log_level="info",
            logging_steps=10,
            logging_strategy="steps",
            lr_scheduler_type=cfg.lr_scheduler_type,
            optim='adamw_torch_fused',         # Fused AdamW for efficiency
            num_train_epochs=cfg.num_epochs,
            output_dir=cfg.model_path,
            overwrite_output_dir=True,
            per_device_train_batch_size=cfg.per_device_batch_size,
            per_device_eval_batch_size=cfg.per_device_batch_size*2,  # Larger eval batch
            report_to="wandb" if cfg.wandb else None,
            save_strategy="steps",
            save_steps=1000,
            save_total_limit=3,               # Keep only 3 most recent checkpoints
            seed=cfg.seed,
            warmup_ratio=cfg.warmup,
            remove_unused_columns=False,
            label_names=["labels"],
            ddp_find_unused_parameters=False,  # DDP optimization
            save_safetensors=False,            # Use pickle format for compatibility
        ),
    )

    train_result = trainer.train(resume_from_checkpoint=cfg.checkpoint)

    # ============================================================================
    # MODEL SAVING AND CLEANUP
    # ============================================================================
    # Save the distilled student model for subsequent evaluation
    if accelerator.is_main_process:
        # Re-enable caching for inference
        trainer.model.config.use_cache = True
        
        # Merge LoRA weights back into base model if LoRA was used
        if cfg.lora:
            trainer.model = trainer.model.merge_and_unload()
        
        torch.cuda.empty_cache()
        
        # Save final model and tokenizer
        final_output_dir = os.path.join(cfg.model_path, "final")
        trainer.save_model(final_output_dir)
        trainer.tokenizer.save_pretrained(final_output_dir)


    accelerator.end_training()

if __name__ == "__main__":
    main()